import {Document, model, Schema, SchemaTypes} from "mongoose";
import {ICompany} from "@coreModule/database/schemas/company/company";
import {normalizeSchemaPermissions} from "@coreModule/database/utilities";
import ownershipPlugin from "@coreModule/database/plugins/ownershipPlugin";
import auditPlugin from "@coreModule/database/plugins/auditPlugin";
import {IOwnershipPluginFields} from "@coreModule/database/types/plugin-fields";
import {addModelData} from "@coreModule/database/collections";
import {validateSchemaDefAgainstMongoose} from "@coreModule/database/utilities/validateSchemaDefAgainstMongoose";
import {PaymentTransactionSchemaDef} from "armonia/src/modules/eCommerce/api/eCommerce/private/paymentTransaction/paymentTransaction.schema-def";
import {applyPaymentTransactionIndexes} from "./paymentTransaction.indexes";
import {paymentTransactionViews} from "./paymentTransaction.views";

export type PaymentGateway = "stripe" | "paypal" | "manual" | "wallet";
export type PaymentTransactionStatus = "pending" | "succeeded" | "failed" | "refunded" | "partially_refunded" | "disputed";
export type PaymentTransactionType = "charge" | "refund" | "payout" | "dispute";

export interface IPaymentTransaction extends Document, IOwnershipPluginFields {
    order: Schema.Types.ObjectId;
    gateway: PaymentGateway;
    type: PaymentTransactionType;
    status: PaymentTransactionStatus;
    amount: number;
    currency: Schema.Types.ObjectId;
    gatewayTransactionId?: string;
    gatewayPaymentMethodId?: string;
    gatewayResponse?: Record<string, unknown>;
    failureReason?: string;
    refundedAmount: number;
    metadata?: Record<string, unknown>;
    company: ICompany;
}

const PaymentTransactionSchema = new Schema<IPaymentTransaction>(
    {
        order: {type: SchemaTypes.ObjectId, ref: "ProductOrder", required: true},
        gateway: {
            type: SchemaTypes.String,
            enum: ["stripe", "paypal", "manual", "wallet"],
            required: true,
        },
        type: {
            type: SchemaTypes.String,
            enum: ["charge", "refund", "payout", "dispute"],
            required: true,
        },
        status: {
            type: SchemaTypes.String,
            enum: ["pending", "succeeded", "failed", "refunded", "partially_refunded", "disputed"],
            default: "pending",
        },
        amount: {type: SchemaTypes.Number, required: true, min: 0},
        currency: {type: SchemaTypes.ObjectId, ref: "Currency", required: true},
        gatewayTransactionId: {type: SchemaTypes.String, trim: true},
        gatewayPaymentMethodId: {type: SchemaTypes.String, trim: true},
        gatewayResponse: {type: SchemaTypes.Mixed},
        failureReason: {type: SchemaTypes.String},
        refundedAmount: {type: SchemaTypes.Number, default: 0, min: 0},
        metadata: {type: SchemaTypes.Mixed},
    },
    {accessMode: "loose"},
);

ownershipPlugin(PaymentTransactionSchema);
auditPlugin(PaymentTransactionSchema);
applyPaymentTransactionIndexes(PaymentTransactionSchema);
const PaymentTransaction = model<IPaymentTransaction>("PaymentTransaction", PaymentTransactionSchema);
normalizeSchemaPermissions(PaymentTransaction);
export default PaymentTransaction;

addModelData(PaymentTransaction, paymentTransactionViews);
// SchemaDef is intentionally empty — PaymentTransactions are system-generated by the payment flow.
// excludePaths: all required/complex fields (enums, objectIds, Mixed types, no SchemaDef equivalents)
validateSchemaDefAgainstMongoose(PaymentTransactionSchema, PaymentTransactionSchemaDef, "PaymentTransaction", ["order", "gateway", "type", "amount", "currency", "refundedAmount", "gatewayResponse", "metadata"]);
